// Vector icon glyphs (Material Symbols path data, 24x24 viewbox), adapted
// from the vayou-slint project's ui/icons.slint, used here under the MIT
// license below. Only the icons CedarApple's player controls need were
// kept; Vayou's own screen layouts, theme and widget styling were
// intentionally left behind - this file is just the icon vocabulary.
//
// MIT License
//
// Copyright (c) 2026 Vayou contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

export component AppIcon {
    in property <string> data;
    in property <brush> color: white;
    in property <length> size: 20px;

    width: size;
    height: size;
    Path {
        commands: root.data;
        fill: root.color;
        fill-rule: evenodd;
        viewbox-width: 24;
        viewbox-height: 24;
        width: 100%;
        height: 100%;
    }
}

export global Ic {
    out property <string> play: "M8 19V5l11 7z";
    out property <string> pause: "M14 19V5h4v14zm-8 0V5h4v14z";
    out property <string> next: "M16.5 18V6h2v12zm-11 0V6l9 6z";
    out property <string> prev: "M5.5 18V6h2v12zm13 0l-9-6l9-6z";
    out property <string> folder-open: "M4 20q-.825 0-1.412-.587T2 18V6q0-.825.588-1.412T4 4h6l2 2h8q.825 0 1.413.588T22 8H11.175l-2-2H4v12l2.4-8h17.1l-2.575 8.575q-.2.65-.737 1.038T19 20zm2.1-2H19l1.8-6H7.9zm0 0l1.8-6zM4 8V6z";
    out property <string> close-x: "M6.4 19L5 17.6l5.6-5.6L5 6.4L6.4 5l5.6 5.6L17.6 5L19 6.4L13.4 12l5.6 5.6l-1.4 1.4l-5.6-5.6z";
}
